-- Crear tabla Productos
CREATE TABLE PRODUCTOS (
    ID_PROD INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    STOCK INT NOT NULL,
    ID_PROV INT NOT NULL,
    ID_IMPUESTO INT NOT NULL,
    CONSTRAINT ID_PROD PRIMARY KEY (ID_PROD),
    FOREIGN KEY (ID_PROV) REFERENCES PROVEEDORES(ID_PROV),
    FOREIGN KEY (ID_IMPUESTO) REFERENCES IMPUESTOSTASAS(ID_IMPUESTO)
);

-- Crear tabla Proveedores
CREATE TABLE PROVEEDORES (
    ID_PROV INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255) NOT NULL,
    CONSTRAINT ID_PROV PRIMARY KEY(ID_PROV)
);

-- Crear tabla Pedidos
CREATE TABLE PEDIDOS (
    ID_PEDIDOS INT NOT NULL,
    FECHA DATE NOT NULL,
    ID_PROD INT NOT NULL,
    CANTIDAD INT NOT NULL,
    CONSTRAINT ID_PEDIDOS PRIMARY KEY (ID_PEDIDOS),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID_PROD)
);

-- Crear tabla Clientes
CREATE TABLE CLIENTES (
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255) NOT NULL,
    CONSTRAINT ID_CLIENTE PRIMARY KEY(ID_CLIENTE)
);

-- Crear tabla Facturas
CREATE TABLE FACTURAS (
    ID_FACTURAS INT NOT NULL,
    FECHA DATE NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_FORMAPAGO INT NOT NULL,
    CONSTRAINT ID_FACTURAS_PK PRIMARY KEY(ID_FACTURAS),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    FOREIGN KEY (ID_FORMAPAGO) REFERENCES FORMASPAGO(ID_FORMAPAGO)
);

-- Crear tabla Detalle de Pedido
CREATE TABLE DETALLEPEDIDO (
    ID_DETALLE INT NOT NULL,
    ID_PEDIDOS INT NOT NULL,
    ID_PROD INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIOUNITARIO DECIMAL(10, 2) NOT NULL,
    IMPORTE DECIMAL(10, 2) NOT NULL,
    CONSTRAINT ID_DETALLE_PK PRIMARY KEY(ID_DETALLE),
    FOREIGN KEY (ID_PEDIDOS) REFERENCES PEDIDOS(ID_PEDIDOS),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID_PROD)
);

-- Crear tabla Almacenes
CREATE TABLE ALMACENES (
    ID_ALMACEN INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    TELEFNO VARCHAR(15) NOT NULL,
    CONSTRAINT PK_ID_ALMACEN PRIMARY KEY(ID_ALMACEN)
);

-- Crear tabla CategoriasProductos
CREATE TABLE CATEGORIASPRODUCTOS (
    ID_CAT_PROD INT NOT NULL,
    NOMBRE VARCHAR(255),
    DESCRIPCION VARCHAR(255),
    CONSTRAINT PK_CAT_PROD PRIMARY KEY(ID_CAT_PROD)
);

-- Crear tabla ProductosAlmacenes (Relación Muchos a Muchos)
CREATE TABLE PRODUCTOSALMACENES (
    ID_PROD INT NOT NULL,
    ID_ALMACEN INT NOT NULL,
    STOCK INT NOT NULL,
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    FOREIGN KEY (ID_ALMACEN) REFERENCES ALMACENES(ID_ALMACEN)
);

-- Crear tabla ProductosCategorias (Relación Muchos a Muchos)
CREATE TABLE PRODUCTOSCATEGORIAS (
    ID_PROD INT NOT NULL,
    ID_CAT_PROD INT NOT NULL,
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    FOREIGN KEY (ID_CAT_PROD) REFERENCES CATEGORIASPRODUCTOS(ID_CAT_PROD)
);

-- Crear tabla Usuarios
CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_ROL INT NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID_USUARIO),
    FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

-- Crear tabla Roles
CREATE TABLE ROLES (
    ID_ROL INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    CONSTRAINT ID_ROL_PK PRIMARY KEY (ID_ROL)
);

-- Crear tabla Descuentos
CREATE TABLE DESCUENTOS (
    ID_DESCUENTO INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    PORCENTAJE DECIMAL(5, 2) NOT NULL,
    FECHAINICIO DATE NOT NULL,
    FECHAFIN DATE NOT NULL,
    CONSTRAINT ID_DESCUENTO_PK PRIMARY KEY (ID_DESCUENTO)
);

CREATE TABLE DESCUENTOSPRODUCTOS (
    ID_DESCUENTO INT NOT NULL,
    ID_PROD INT NOT NULL,
    FOREIGN KEY (ID_DESCUENTO) REFERENCES DESCUENTOS(ID_DESCUENTO),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUCTOS(ID_PROD)
);

-- Crear tabla Ofertas
CREATE TABLE OFERTAS (
    ID_OFERTAS INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    ID_DESCUENTO INT NOT NULL,
    FECHAINICIO DATE NOT NULL,
    FECHAFIN DATE NOT NULL,
    CONSTRAINT ID_OFERTAS_PK PRIMARY KEY (ID_OFERTAS),
    FOREIGN KEY (ID_DESCUENTO) REFERENCES DESCUENTOS(ID_DESCUENTO)
);

CREATE TABLE OFERTASCLIENTES (
    ID_OFERTA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_OFERTA) REFERENCES OFERTAS(ID_OFERTA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

-- Crear tabla UbicacionesFisicas
CREATE TABLE UBICACIONESFISICAS (
    ID_UBICACIONES INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    ID_ALMACEN INT NOT NULL,
    CONSTRAINT ID_UBICACIONES PRIMARY KEY (ID_UBICACIONES),
    FOREIGN KEY (ID_ALMACEN) REFERENCES ALMACENES(ID_ALMACEN)
);

-- Crear tabla ImpuestosTasas
CREATE TABLE IMPUESTOSTASAS (
    ID_IMPUESTO INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    PORCENTAJE DECIMAL(5, 2) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CONSTRAINT ID_IMPUESTO_PK PRIMARY KEY(ID_IMPUESTO)
);

-- Crear tabla FormasPago
CREATE TABLE FORMASPAGO (
    ID_FORMAPAGO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    DETALLE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_FormaPago PRIMARY KEY(ID_FORMAPAGO)
);

-- Crear tabla AuditoriaCambios
CREATE TABLE AUDITORIACAMBIOS (
    ID_AUDITORIA INT NOT NULL,
    TABLAAFECTADA VARCHAR(100) NOT NULL,
    ID_REGISTROAFECTADO INT NOT NULL,
    CAMPOAFECTADO VARCHAR(100) NOT NULL,
    VALORANTERIOR VARCHAR(100) NOT NULL,
    VALORNUEVO VARCHAR(100) NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    USUARIO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_AuditoriaCampos PRIMARY KEY(ID_AUDITORIA)
);

-- Crear tabla HistorialPedidos
CREATE TABLE HISTORIALPEDIDOS (
    ID_HISTORIAL INT NOT NULL,
    ID_PEDIDOS INT NOT NULL,
    ESTADOANTERIOR VARCHAR(255) NOT NULL,
    ESTADONUEVO VARCHAR(255) NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    CONSTRAINT ID_HISTORIAL PRIMARY KEY(ID_HISTORIAL),
    FOREIGN KEY (ID_PEDIDOS) REFERENCES PEDIDOS(ID_PEDIDOS),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);